### ISSUE TITLE
Enable oasgraph-based aggregation of multiple REST endpoints with identical OAS descriptions

### ISSUE THREAD

**Issue by alansill** [IBM/openapi-to-graphql#136]
I have a situation in which there are multiple independent REST endpoints, each of which uses an identical OAS description and therefore each works fine with oasgraph as an individual server, but I would like to be able to query the set of them using a GraphQL server that allows passing of the base URL of the REST endpoint as a parameter in the GraphQL query. Essentially, I'd like to subsume the translated GraphQL schema for each of the endpoints with one more layer on top of it, which is the base URL of the endpoint server. This would allow me to access the whole set of identical endpoints at once with and identical query or command, with oasgraph serving the higher-level GraphQL schema in which the base URL (and perhaps port, with ports being identical also across the REST endpoints) can be specified as a set with controllable members.

Is this possible, or can you suggest another way to do this?

**Comment by ErikWittern** [comment]
Hey @alansill, maybe already some pointers towards answering your question: @Alan-Cha recently started building out support for passing multiple OASs to OASGraph (see #82). The current state of this implementation is reflected in the master branch, but not yet in a release of OASGraph.

That said, you could achieve something of what you outline by passing multiple OASs, each of which would have its unique base URL defined.

However, be aware that when these OASs are identical, as you say, naming collisions will occur. I.e., the `User` JSON schema defined in every one of these OASs will receive its own name in the resulting GraphQL API, likely `User`, `User2`, `User3`, etc. This may not be ideal from a usability point of view.

Passing the URL to call in a parameter, rather than relying on the base URL defined in the OAS, is from my point of view not something we would want to support, as I think this behavior would be too specialized and not as intended by the OpenAPI Specification. Maybe you feel differently, though, and I would be happy to hear further arguments in that case.

**Comment by alansill** [comment]
Hi,

The goal would be to build an API gateway that can work with multiple base URLs, each of which deploys an identical or close-to-identical API. I could build the gateway as REST-only, with OASGraph used on top of that as a single endpoint layer, which it is now, but would like to achieve all of this in one code base.

The reason that the multiple endpoints at the different base URLs are identical is that thye control identical, multiply-deployed instances of the same functionality. Think of an IoT situation in whihc you have lots of simple REST endpoints, each of which is identical or nearly so, and need to control them in aggregate.

**Comment by ErikWittern** [comment]
@alansill Thank you for providing these details!

While I understand the use-case, I don't necessarily think it would be a good thing to support passing base URLs as arguments in queries, because it moves OASGraph away from a more direct mapping to the OpenAPI Specification.

If you wanted to look into this issue yourself, you could look into using a `viewer`, as we do to allow users to pass authentication credentials: https://github.com/strongloop/oasgraph/blob/master/packages/oasgraph/src/auth_builder.ts#L47
