### ISSUE TITLE
Pass headers to backend

### ISSUE THREAD

**Issue by YifengWong** [IBM/openapi-to-graphql#234]
Instead of using apikey viewer things, I want to pass my cookie each request in header to backend, just pass ALL Cookie, any resolution? thx

**Comment by Alan-Cha** [comment]
Hi! Sorry for the late response. I believe this is possible using the `requestOptions` (to pass the cookie) and `viewer` (to remove viewers) [options](https://github.com/IBM/openapi-to-graphql/tree/master/packages/openapi-to-graphql#options).

***

See an example [here](https://github.com/IBM/openapi-to-graphql/blob/0ecb7f7573db0c6931ad5d7e12b59d94db7e521b/packages/openapi-to-graphql/test/authentication.test.ts#L301).

```
const { schema } = await openapiToGraphql.createGraphQlSchema(oas, {
  viewer: false,
  requestOptions: {
    headers: {
      cookie: 'access_token=abcdef'
    },
    url: undefined
  }
})
```

***

The `requestOptions` directly exposes the [Request.js](https://www.npmjs.com/package/request) options used by the resolvers to call the REST API. You can find other options [here](https://github.com/request/request#requestoptions-callback).

**Comment by YifengWong** [comment]
@Alan-Cha Thanks for your response. In fact I want to pass different header in each request to backend, I have read the source code, it seems that it is unachievable.

Is it possible to add a requestOptions to allow user to transfer some fields in header for each request? such as

`
requestOptions: {
  penetrateHeader: ['cookie']
}
`

in resolver builder:
`
if (penetrateHeader.length > 0) {
	penetrateHeader.forEach(fieldName => {
		options.headers[fieldName] = ctx.headers[fieldName]
	})
}
`

**Comment by Alan-Cha** [comment]
@YifengWong Happy to help! So you want the user to be able to change the header in each request? If so, it should just be a matter of defining header parameters in the OAS. Then, OtG will automatically create an interface such that each operation (requiring header parameters) will have additional arguments that the user can use for header parameters. 

Is this what you mean?

***

[Here](https://github.com/IBM/openapi-to-graphql/blob/f44205a9035ac2db08cc6ebf9d499dc67520e0fc/packages/openapi-to-graphql/test/example_api.test.ts#L569) is an example of a query that has arguments for passing cookie values.

[Here](https://github.com/IBM/openapi-to-graphql/blob/f44205a9035ac2db08cc6ebf9d499dc67520e0fc/packages/openapi-to-graphql/test/fixtures/example_oas.json#L256) is the OAS.

Let me know if this is what you're looking for!

**Comment by YifengWong** [comment]
@Alan-Cha If I define a parameter cookie in OAS, I should set it in my GQL query request body, instead GQL query headers. WAHT I want is to penetrate the GQL request header field in each request to source backend.

**Comment by PalmerEk** [comment]
I have the same need.  Multiple consumers each with their own API key.  I need their key passed through to the REST API (viewerApiKey) but I would prefer to send the key as a header (perhaps via an axios interceptor for example)  and keep the schema a bit cleaner.

While it doesn't appear possible I think there is a somewhat reasonable solution.  If you allow the headers (and or requestOptions) opts to be an object or function:

```
const { schema } = await openapiToGraphql.createGraphQlSchema(oas, {
  viewer: false,
  headers: (req) => {
    return {
      ...req.headers
    }
  }
})
```

then in getResolver change where your passing them on to something like:

```
// Headers:
let additionalHeaders = data.options.headers;
if(typeof data.options.headers === 'function') additionalHeaders = data.options.headers(ctx);

for (let header in additionalHeaders) {
      options.headers[header] = additionalHeaders[header];
}
```
Only 1/2 baked but that's the gist

**Comment by Alan-Cha** [comment]
@PalmerEk I think this makes sense. This also give us a reason to keep the original `header` option, which for a long time seemed to be redundant thanks to the new `requestOptions` option.

**Comment by yoonslee** [comment]
@Alan-Cha Yes, having the `headers` option be a function as opposed to a static object would be super useful.

I am attempting to use `tokenJSONpath` -- as a workaround -- to pass a token, but it adds the `Bearer <token>` prefix, which I understand is the OAuth way of doing things (I am working with an API that requires `Basic` instead). Is there any way to edit the header value before the request gets sent?

The `viewer` "pattern" functionally works, but I do not enjoy the experience of nesting and duplication of queries and mutations for `viewerApiKey` and `viewerAnyAuth`.

**Comment by gtamas** [comment]
@Alan-Cha  @ErikWittern 

Are there any news about this one?

I can see that multiple there are multiple discussions related to this topic and there is even a PR which hasn't been accepted yet. However, there seem to be no result..

Passing custom headers to each request would be user useful. One use case is transparent authentication. I would need to pass a token and username to authenticate the request, but this doesn't seem to be possible right now.
Another use case is debugging: A unique ID could be attached to each request, so we can track them in the logs later.
Yet another use case would be request "grouping": Since a GraphQL request may results in several REST calls, I need to be able to identify this "group" later, for debugging purposes. So attaching a group-id header to each request generated by a given GQL query would be very useful..

Besides, this not only about headers. We could pass query string params in a similar way, or attach arbitrary data to request body etc.

Also, currently there seem to be no API for writing custom Viewers, which might be another solution.

Anyway, here is my use case: 

Right now, I just need to implement transparent authentication by passing 2 custom headers to each request. How can I achieve this with the currently available functionality?

I can understand that one way to accomplish this is via OpenAPI schema (header parameters). 
Is this the only way? I might not be able to change the OAS. So it would be easier for me to do this programmatically.

Thanks in advance!

**Comment by gtamas** [comment]
Our app generates the GQL schema only once (on startup).

Therefore I need a way to inject those headers without calling the createGraphQlSchema() function again.

**Comment by Alan-Cha** [comment]
@gtamas Actually there is a PR in the works right now #270, filed by @yoonslee. I believe all that is missing are some test cases. I can try to add them in later today.

What would your ideal solution be in regards to `requestOptions`?

**Comment by gtamas** [comment]
@Alan-Cha 

Yes this is the PR I mentioned. It would be great to add something like this. 
But maybe it would be even better if we could modify other parts of the request too, such as the body, query params, url (route) params etc.
I'm not sure yet what's the best way to achieve this, I need to look more into the OtG  code, it's still kinda new to me :). 
All I'm saying is that probably it would best to extend this PR / idea a bit further and provide a more general solution which covers all the important request attributes.

**Comment by Alan-Cha** [comment]
With version v2.2.0, headers can now be dynamically set using a function. I believe we can finally close this issue.
