### ISSUE TITLE
Missing validation for server url

### ISSUE THREAD

**Issue by wtrocki** [IBM/openapi-to-graphql#239]
**Describe the bug**
When starting server basing on the definition tooling is not checking if the server url is provided. Documentation is not specifying what fields that are usually optional are required to run server (URL)

**To Reproduce**
1. Download https://gist.github.com/wtrocki/2ece5c69bc585d36d601b0ce701103f7
2. openapi-to-graphql example-task.yaml                                                                                                      3. Execute tasks query

```
{
  "errors": [
    {
      "message": "Invalid URI \"/tasks\"",
      "locations": [
        {
          "line": 31,
          "column": 3
        }
      ],
      "path": [
        "tasks"
      ]
    }
  ],
  "data": {
    "tasks": null
  }
}
```

**Expected behavior**
The server should validate the existence of the url and fail to start.

**Screenshots**
<img width="482" alt="Screenshot 2019-09-06 at 12 33 55" src="https://user-images.githubusercontent.com/981838/64425034-9daab300-d0a2-11e9-98b6-ad42f428dc40.png">

Happy to contribute and fix this problem uppon agreement.

**Comment by Alan-Cha** [comment]
To be honest, I'm more familiar with OAS 3 than Swagger but I believe the problem is that the Swagger does not have a `host` or a `basePath` (`servers` object equivalent in OAS 3) to build the URL (i.e. we want to call something like "https://myapi.com/tasks" but we were only provided the path "/tasks"). 

Perhaps the problem is how we are reporting the problem. If you have any suggestions, feel free to speak them!

**Comment by wtrocki** [comment]
Having simple check for OAS2/OAS3 if there is server url is provided. 
I was using Apicurio (https://www.apicur.io/) to build OAS3 definition so it looks they do not provide url by default.

**Comment by wtrocki** [comment]
I found url `--url` command that resolves the problem by giving a way to override sever url
