### ISSUE TITLE
Data Loader support

### ISSUE THREAD

**Issue by wtrocki** [IBM/openapi-to-graphql#240]
Investigate how to support Facebook data loader in generated resolver layer.

**Comment by Alan-Cha** [comment]
Can't wait!!! 😄

**Comment by wtrocki** [comment]
I have done a quick investigation and found out that there are 3 major challenges of doing data loader support:

- Moving towards caching resources will mean a complete refactor of the resolver layer
that has some concepts that I'm not fully understanding at the moment.
- There is a problem of finding cache key - this is usually done explicitly by users creating data loaders for concrete business objects.
- Generic resolvers are doing tons of extra stuff that might not be needed for specific use cases

Now I understand why custom resolvers were introduced and how much value they provide. 
However, there is also a problem with the architecture of the cli that is creating server inside cli.

To implement most of the stuff like user/auth etc. people will usually need to apply some extra fields to context - including loaders. With the current architecture, there is no possibility to do it 
as server startup logic is in cli and cannot be controlled by software. (which is fine for quick demo/testing)

I think generally the library is much more useful as it can be used by any other server (like Apollo GraphQL etc) and the resolver layer is also built for demo purposes and for production use cases it should be probably replaced with some custom one. 

I think it will be cool if underlying api will return `typedefs` and `resolvers` as separate objects in alternative method. This will make entire library much more flexible - currently there is need for decomposing schema back or use schema that was saved to file. This change will make entire library much more friendly for library use cases. 

This will mean that people who care for performance can use https://github.com/zalando-incubator/graphql-jit etc. along with the library
Example:
```javascript
import { createGraphQLTypeDefs } from "openapi-to-graphql"

cosnt {typeDefs,resolvers} =  createGraphQLTypeDefs(oapi);
export const schema = makeExecutableSchema({
  typeDefs,
  resolvers,
});
```

WDYT? I'm happy to make the change as part of the new api and create separate sample app that is performant etc.

**Comment by ErikWittern** [comment]
@wtrocki Thank you also for this proposal!

I am not 100% sure about data loaders, and the comments you make. Specifically, why do you say that "Moving towards caching resources will mean a complete refactor of the resolver layer"? Irrespective of data loaders, one way that caching can be implemented is: use the HTTP request to make (i.e., the URL, payload, and headers) to generate a hash, which then identifies the response in an ephemeral map (e.g., https://www.npmjs.com/package/node-cache). If a response is cached, return it from the cache, otherwise populate the cache. This should be doable with the current resolver functions.

You outline a second idea, namely to allow users to obtain type definitions and related resolver functions in maps, instead of obtaining the monolithic schema. I agree that this is an interesting idea that would improve flexibility of our library. I think this should be reflected in a dedicated issue, though. I am also wondering if the GraphQL reference implementation does allow to use the proposed maps to generated a schema? I don't think it is a good idea to generate this output if it is only usable with Apollo tools.

**Comment by wtrocki** [comment]
I cannot agree more. It will be good to have http level cache that will have cached data per request and yes data loader will not make much sense here. 

Generating hash of payload is great alternative to not having clear information about id but I will need to check if cost of hash for every item might not defeat the purpose of having better performance. Caching outside single request is risky business as clients can get outdated data.

In relation to second problem. `makeExecutableSchema` is default way to build graphql API in both Apollo and graphql.js. Both frameworks allow to pass rootResolver and definitions separately as alternative to passing compiled schema. My plan is to play with API and send PR.

**Comment by ErikWittern** [comment]
@wtrocki Caching on the HTTP level sounds very good! I actually implemented this (hackishly) once in an application with some custom resolvers, and it worked well.

Great to hear that `makeExecutableSchema` is a default way of doing things. I really like your proposal of adding a `createGraphQLTypeDefs` function!

**Comment by wtrocki** [comment]
In case someone will look for this problem in the future.

The found solution that does not require any change in OtG
The way I have approached that is that I have used https://github.com/ardatan/graphql-toolkit `extractResolversFromSchema` method. 

```javascript
  let { schema } = await createGraphQlSchema
  const typeDefs = printSchema(schema)
  const rootValue = extractResolversFromSchema(schema)
  graphqlHttp({
     ... 
    typeDefs,
    rootValue
    context: {loaders: createLoaders()}
 }); 
```

**Comment by cancan101** [comment]
@wtrocki can you give a bit more information on how you ended up solving this?
