### ISSUE TITLE
Combine schema mitigation using JSON GraphQL type

### ISSUE THREAD

**Issue by Alan-Cha** [IBM/openapi-to-graphql#244]
We try to create fallbacks wherever we can to maximize successful GraphQL wrappers. This means that if we encounter either an error (e.g. a mistake in the OAS) or something ambiguous, we try to find an reasonable alternative route so that we can report the error (as a warning) but still create a wrapper. 

***

Many potential conflicts can occur with the combining schema mechanisms in JSON schema, i.e. `allOf`, `anyOf`, `oneOf`, and `not`. 

This can be conflicts within the JSON schema itself, for example: 

```
{
  "allOf": [
    { "type": "string" },
    { "type": "number" }
  ]
}
```

... or conflicts with translating to GraphQL. For example, we feel that `oneOf` maps nicely to the GraphQL unions. However, GraphQL unions have very strict requirements, namely that all member types must be object types and cannot be composed of other unions. JSON schema makes no restrictions. 

Currently, if a member schema does not fit the requirements, we simply ignore it (and report it). I wonder if this is the best way to move forward as JSON schema provides a lot of flexibility and we cannot simply assume that the OAS provider intended it to map to something akin to GraphQL unions. 

Instead of simply ignoring member types, perhaps, we should map problematic fields/schemas to [GraphQL JSON type](https://github.com/taion/graphql-type-json).

**Comment by wtrocki** [comment]
My 2c (hope you do not mind)

`GraphQL unions` are the generally tricky part and from personal experience and no go zone in terms of generic resolver layer (been there) that making entire processing quite complex. Unions can rely on common interface - as far I remember there is no way to describe interfaces in the openapi. The way I see is that for the complex use cases can be handled by people saving schema and making some manual tweaks like:

- Adding scalars ( like Date or https://github.com/Urigo/graphql-scalars)
- Adding directives
- Adding interfaces etc.

For some of those people might need to drop some extra code in form of custom resolver but this will be much simple rather than trying to cover all those in generic engine.

I have tested `openapi-to-graphql` with large OpenApi with tons of stuff I have and it was working for all the cases. 

I have done quick spike trying to replicate "google translate effect":

Use complex GraphQL schema to generate restful API (using https://sofa-api.com/) and then generate Oapi definition from it. Then I used Open-API-GraphQL to generate the same schema. 
As result all metadata visible above were lost - along with some extra things that were related to the way that sofa exposes GraphQL API over REST

The main challenge is to not add additional complexity to library that does things right just to support 1% of the use cases that the community might not need to use.

**Comment by Alan-Cha** [comment]
@wtrocki Thank you so much for your insight!!! This is all super helpful! 

I see your point. Unions make everything much more complex. Perhaps it would be easier, for both contributors and users of OtG, to simply make OtG more extensible and/or provide guidelines on creating OASs that would work better with OtG. However, it's difficult to figure out how to move forward because of one vital question and that is "how are people using OtG?". 

***

@ErikWittern and I started working on this project because it seemed like an interesting research question. It's different now that we've open sourced because we want to create something that people want to use and work on. I think in order to do that properly, we should have a good idea on _how_ people want to use OtG and unfortunately, we don't. 

For example, we don't know if people use OtG to play around with GraphQL or if they want to use it as a vital component in their backend. Do people use OtG by itself? Or do they use it in some kind of larger pipeline, using multiple tools to create an optimal GraphQL interface? We don't know if people are willing to make changes in their OASs so that it will work better with OtG. If they are, then would they be willing to make changes in their REST APIs as well? 

As a result, it's difficult to cater our work for our users because we don't know who they are and why they're using OtG. For the most part, we have tried to cater towards people just starting out with GraphQL. We created a CLI and offer many mitigations to make OtG an optimal entry point for beginners. 

***

Coming back to the discussion, we're not sure if people are willing to do all of your suggestions in order to get more functionality out of OtG. It would be easy to just default onto a JSON type or to resolve these schemas the way we resolve `allOf`, which is to create one huge object type containing the superset of all properties (if possible).  

One advantage of deliberately trying to create unions is that we can preserve some typing information and as a result, leverage links to allow for more deeply nested queries. Perhaps we can still do something similar with an `allOf` approach but it'll be messy. With JSON type, not at all. 

In any case, I've already done a lot of work with unions in #232 and so far, we have no `oneOf` (or `anyOf` and `not`) resolution so I feel that we might end up checking it in. However, we can easily change our approach as we continue this discussion. 

***

It makes me very happy to hear that OtG is working for your particular use case! Again, it's always nice to hear how people are using it, if it is indeed working for them, and if not the problems, so we develop a better sense on how to move forward. 

This Google translate experiment is also very interesting! I would love to talk to you about all of this if you are willing.

**Comment by wtrocki** [comment]
> As a result, it's difficult to cater our work for our users because we don't know who they are and why they're using OtG. 

I absolutely love this library and I think it does so many things right. 
I think this library covers a couple really important and not solved problems in GraphQL community:

- migration from REST to GraphQL done using standards
- GraphQL Api Gateway generation using CLI for quick getting started
- Nice Command line tool for various tooling that can be added to any existing GraphQL project
- Extensive support for mapping OAS to GraphQL Schema
- out of the box REST mapping resolver layer.

What this library does not offer at the moment but can do it easily:

- Out of the box support for different frameworks like apollo (Resolvers format is specific to graphql-js)
- Production-ready GraphQL API gateway (possibly in form of custom code/wrappers)

**Comment by Alan-Cha** [comment]
We eventually went with the route of converting `oneOf` into unions and `anyOf` into object types (if applicable) in v2.0.0. We also have much more robust fallback mechanisms.
