### ISSUE TITLE
How can I handle "Error: Invalid specification provided"

### ISSUE THREAD

**Issue by jiheapark** [IBM/openapi-to-graphql#324]
I used
```javascript
const { createGraphQLSchema } = require("openapi-to-graphql");

const { schema, report } = await createGraphQLSchema( openapi-url );
```

like

```javascript
const { schema, report } = await createGraphQLSchema('https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/api-with-examples.yaml');
```

or saved openapi file to my computer and tried

```javascript
const { schema, report } = await createGraphQLSchema( openapi-file-path );
```

I always got this error

```
(node:98189) UnhandledPromiseRejectionWarning: Error: Invalid specification provided
```

when I check validation of my swagger on https://editor.swagger.io/
The error I got is "Query strings in paths are not allowed."
Is "Query strings in paths are not allowed." error has any problem using openapi-to-graphql?

![스크린샷 2020-06-10 오후 3 40 01](https://user-images.githubusercontent.com/26865541/84235359-aef08680-ab30-11ea-8254-6b6cf382a2be.png)

what should I do?
Please help me.

**Comment by Alan-Cha** [comment]
This is most likely coming from our Swagger to OAS translator/OAS validator [swagger2openapi](https://www.npmjs.com/package/swagger2openapi).

You can use the online tool to verify: https://mermade.org.uk/openapi-converter

***

If you do indeed get this error, then unfortunately, you will probably have to go report this error to [swagger2openapi](https://github.com/Mermade/oas-kit). 

This error sounds like a valid error however. I believe query strings should be expressed using the (parameter object)[https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#parameterObject] instead of being hard coded in the path. Is it possible to use the parameter object instead?
