### ISSUE TITLE
Unable to convert Swagger 2.0 to GraphQL

### ISSUE THREAD

**Issue by KolbySisk** [IBM/openapi-to-graphql#396]
I'm currently using `swagger-to-graphql` and was hoping I could easily replace it with `openapi-to-graphql`. I replaced the `createSchema` call with `createGraphQLSchema` and hoped for the best.

I got this error when I ran it:
`UnhandledPromiseRejectionWarning: Could not convert Swagger to OpenAPI Specification. (Patchable) parameter.type is mandatory for non-body parameters`

I'm using a Swagger 2.0 object and calling:
`const { schema, report } = await createGraphQLSchema(swaggerObject);`

Is there something I'm doing wrong?

**Comment by KolbySisk** [comment]
I have a feeling the issue is related to properties that don't have a type, but instead just a ref:

```
"definitions": {
    "FetchThingDto": {
      "type": "object",
      "properties": {
        "someNumber": { "$ref": "#/definitions/Optional«int»" },
```

Could that be the cause of this error?

**Comment by Alan-Cha** [comment]
@KolbySisk This error is from the [Swagger2OpenAPI](https://github.com/Mermade/oas-kit/tree/master/packages/swagger2openapi) module, that we use to convert Swaggers into OpenAPIs.

I would recommend playing around with it to see what is wrong with your OAS. Their convertor is available online [here](https://mermade.org.uk/openapi-converter) as well.

We do handle refs so I am not sure what the problem is... Sorry! If you would like to provide your OAS or a sample of it, then I can take a look at it myself. With what you have provided so far, I can only do so much.

**Comment by KolbySisk** [comment]
Thanks for the link to the convertor, really useful. I was able to paste my swagger string and convert it without error.

**Comment by florin-f-manea** [comment]
Try:
 **const { schema, report } = await createGraphQLSchema(swaggerObject, { patch: true });**
It looks like the schema you are using misses to provide the parameter type (for one or more parameters); by using the configuration { patch: true } a fallback to **string** will be applied

**Comment by florin-f-manea** [comment]
Sorry, should be:
**const { schema, report } = await createGraphQLSchema(swaggerObject, {swagger2OpenAPIOptions: { patch: true } });**

**Comment by KolbySisk** [comment]
That appears to have worked, ty @florin-f-manea!

Seems the documentation could benefit by having this included.
