### ISSUE TITLE
OASGraph ignores valid API methods that return 204

### ISSUE THREAD

**Issue by laredo** [IBM/openapi-to-graphql#57]
An HTTP status of 204 indicates "No content on the response". When OASGraph encounters an operation with no response body, it will ignore it. 

For example, here is an [OAS](https://github.com/strongloop/oasgraph/files/2465960/openapi.txt)  that uses the 204 HTTP status.

**Comment by dougal83** [comment]
With loopback/cli creating interfaces using 204, will there be any changes to handle this?  No schema is provided and there is no logical reason to include one.

lb4 controller excerpt:
```ts
@del('/todos/{id}', {
    responses: {
      '204': {
        description: 'Todo DELETE success'
      },
    },
  })
  async deleteById(@param.path.number('id') id: number): Promise<void> {
    await this.todoRepository.deleteById(id);
  }
```
Naturally leads to openapi.json without a schema leading to:
```json
"warnings": [
    {
      "type": "MissingResponseSchema",
      "message": "Operation 'DELETE /todos/{id}' has no (valid) response schema.",
      "mitigation": "Ignore operation"
    },
]
```
Could this awesome tool be updated to accommodate?

**Comment by Alan-Cha** [comment]
@dougal83 Thanks for the compliment! Yes, we are trying to address the problem but we haven't found the best solution. The issue is that REST is much more expressive than GraphQL. While REST can express calls that return no response (such as a 204), GraphQL cannot express objects that return no fields. 

We could resolve this issue by defaulting to a placeholder field or a nullable field. However, this solution presents a new set of issues regarding whether this strategy follows good design practices (creating new fields that do not have any real intended uses), how to convey these changes to the user and most importantly, whether we should default to this behavior at all. Do we want really want to start changing things around behind the scenes for the sake of completeness? What about consistency?

I think we can at least add an option to handle 204s for now.

**Comment by dougal83** [comment]
I appreciate your need to evaluate the scope of the implementation. From my perspective I'd see it as being nice to have functional coverage of the loopback-next examples as things move forward.

Is it possible to define an interface to return void type for when 204 is specified? I've seen ideas that say return an ID for deletions but the intent of the 204 is not satisfied if being pernickety.

**Comment by Alan-Cha** [comment]
Yeah, I understand. It doesn't look good if we cannot fully wrap the LoopBack example APIs. We're working on it!

Unfortunately no, there is no void type. The best we can do is set it to a nullable and let it return a null.

**Comment by Ellomend** [comment]
i think its a part of bigger problem.
In reality REST APIs in legacy enviroments often miss some of the specs or follow them in loose manner.  Often one can encounter REST API which not spec complient in part and there no way to fix or alter them.
And there no clean way for monkey-patching those issues. Converter or works good, or not works at all.
As i see it - converter should have option for control over specific endpoints or responses in sane way.
Ideal solution would be customizable to tame all the wild rest apis via extensible lib.

**Comment by dougal83** [comment]
@Ellomend 
Wouldn't say using lb4 to consume non-spec compliant APIs and using it to produce an openapi spec compliant endpoint alleviate that issue?  I would have thought then OASGraph can focus on consuming a spec compliant api with a decent set of use cases to cover from loopback-next examples.
